### ISSUE TITLE
Any plans migrating to React 18+?

### ISSUE THREAD

**Issue by KieranTH** [player-ui/player#351]
**Is your feature request related to a problem? Please describe.**

Migration to React 18.

**Describe the solution you'd like**

A plan on whether React 18 migration should attempted.

I've spent the past day trying to migrate Player to React 18 myself in a fork. There are a few old and outdated dependencies currently being used. I imagine there would be substantial effort to continue this migration. 

It seems like a few of these outdated dependencies are from the docs site, whilst the main ones attached to Player itself are React, React-DOM and Typescript (As my current depth of changes have found anyway) - which is also quite an undertaking. 

As other projects by the community proceed to use newer versions of React, the peer dependencies attached to Player will just cause Node install errors. 

Are there any thoughts on this and any worries / concerns?

Cheers!

**Comment by adierkens** [comment]
Most of our major refactors (including the update to `react@18.12`) are staged on the `bazel-6` branch https://github.com/player-ui/player/pull/252

There were some pretty major changes to our builds (we may also go straight to bazel 7 now), in addition to updating all of the dependencies across the project to the latest. We're still waiting on a few other updates (android & jvm builds, etc) in order to get canary builds out to start testing, but we are working towards releasing support for react@18 soon.

**Comment by kierancap** [comment]
> Most of our major refactors (including the update to `react@18`) are staged on the `bazel-6` branch #252
> 
> There were some pretty major changes to our builds (we may also go straight to bazel 7 now), in addition to updating all of the dependencies across the project to the latest. We're still waiting on a few other updates (android & jvm builds, etc) in order to get canary builds out to start testing, but we are working towards releasing support for react@18 soon.

Appreciate the quick response. Glad to hear!

I'll keep an eye out for those canary versions :)
